<a href="https://colab.research.google.com/github/Rojinar8/Machine-Learning/blob/main/Data_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Euclidean using math as nt
import math as nt
x=[1,2,3]
y=[4,5,6]
print(nt.dist(x,y))


5.196152422706632


In [4]:
# Euclidean using numpy as np
import numpy as np
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
sum=np.sum(np.square(x-y))
print(np.sqrt(sum))

5.196152422706632


In [5]:
import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y= np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

result_dot = np.dot(x, y)
print("Matrix multiplication using np.dot():\n", result_dot)

Matrix multiplication using np.dot():
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
