<a href="https://colab.research.google.com/github/rojinarai2/Machine-Learning/blob/main/Introduction/numpy_5th_sem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introduction to Numpy

What we will cover?

*   Creating single dimensional arrays
*   Multidimensional arrays


*   Randomly generated arrays
*   Element wise operations

*   Summarizing operations








###Single dimensional arrays

In [ ]:
import numpy as np

In [ ]:
#create an array with all the elements to be zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
#creating an array with all elements 1
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
#create an array of size 10 with all elements 3
np.full(10,3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [ ]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [ ]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
#create an array with evenly spaced numbers within a specified range
np.linspace(0,100,12)

array([  0.        ,   9.09090909,  18.18181818,  27.27272727,
        36.36363636,  45.45454545,  54.54545455,  63.63636364,
        72.72727273,  81.81818182,  90.90909091, 100.        ])

###Multidimensional arrays

In [ ]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
a=np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a[0,1]=20
a

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [ ]:
a[0:1]=20
print(a)

[[20 20 20]
 [ 4  5  6]
 [ 7  8  9]]


In [ ]:
a[2]=[1]
a

array([[20, 20, 20],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [ ]:
a[:,2]=[2]
a

array([[20, 20,  2],
       [ 4,  5,  2],
       [ 1,  1,  2]])

In [ ]:
matrix=np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
matrix=np.full((3,3),10)
matrix

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

### Randomly generated arrays


In [ ]:
np.random.rand(5)

array([0.94088584, 0.96887002, 0.32918549, 0.10884129, 0.00765556])

In [ ]:
np.random.seed(80)
np.random.rand(5)

array([0.52191572, 0.69940637, 0.26986897, 0.67448187, 0.90807208])

In [ ]:
np.random.randn(5,2)

array([[-1.03446493,  0.66424004],
       [-1.13937438, -0.89472205],
       [-0.2207972 , -0.43007258],
       [ 1.19972246,  0.1222967 ],
       [ 0.54794733, -0.52658091]])

In [ ]:
np.random.randint(low=0,high=100,size=(5,2))

array([[ 7, 69],
       [96, 56],
       [15,  3],
       [94, 39],
       [51, 94]])

### Element wise operation on entire arrays element by element

In [ ]:
import numpy as np
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
b=(10+(a*2))
b

array([10, 12, 14, 16, 18])

In [ ]:
#comparison opeartions
a

array([0, 1, 2, 3, 4])

In [ ]:
a>=2

array([False, False,  True,  True,  True])

In [ ]:
a>b

array([False, False, False, False, False])

In [ ]:
#summarizing of the data
#Numpy provides functions for summarizing array data
a

array([0, 1, 2, 3, 4])

In [ ]:
a.std()

1.4142135623730951

In [ ]:
a.min()

0

In [ ]:
a.max()

4

In [ ]:
a.sum()

10